### PR TITLE
Change PWM port layout back to binary

### LINKED ISSUE #33: Use nice PWM port layout
Previously we had a nice binary layout for the PWM ports for the drivetrain Victors. Now they're assigned somewhat arbitrarily. Would be nice to move them back to where they were before. Should be quite an easy task.

### PR DESCRIPTION
**Pull request by ianzullo**
Resolves #33

### CODE REVIEW

**Review by ArchdukeTim — APPROVED** [review]
Make sure to change the plugs on the robot as well

**Review by AndrewLester — APPROVED** [review]
Confirmed wires changed

**Review by ErikBoesen — APPROVED** [review]
Looks good, thank you!

**Comment by ErikBoesen** [comment]
@AndrewLester I'm okay with you merging this kind of thing too.

**Comment by AndrewLester** [comment]
@ErikBoesen This is merged using rebase and merge, right?

**Comment by ErikBoesen** [comment]
@AndrewLester Yeah, I typically use squash when the commit is named wrong or the commits aren't very distinct or the history is otherwise messy. Otherwise, rebase works pretty well.

**Pull request merged**
